
import "@/styles/globals.css";
import Head from "next/head";
import { Provider } from "react-redux";
import store from "@/src/redux/store/store";
import Navbar from "@/src/layouts/layout1/website/navbar/Navbar";
import Navmobi from "@/src/layouts/layout1/mobile/navbar/Navmobi";

export default function App({ Component, pageProps }) {
  
  return (
    <>
      <Head>
        <title>Techpyro Restaurant</title>
        <link
          rel="stylesheet"
          type="text/css"
          charset="UTF-8"
          href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick.min.css"
        />
        <link
          rel="stylesheet"
          type="text/css"
          href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick-theme.min.css"
        />
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css"
          integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65"
          crossorigin="anonymous"
        />
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Provider store={store}>
      <Navbar/>
      <Navmobi />
          <Component {...pageProps} />
      </Provider>
    </>
  );
}
